# Generated by Django 5.0.1 on 2024-02-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_orderitem_product_customeradddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeradddress',
            name='default_address',
            field=models.BooleanField(default=True),
        ),
    ]
