# Generated by Django 5.0.1 on 2024-02-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_eng', models.CharField(max_length=200)),
                ('last_name_eng', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('mobile_portfolio', models.PositiveBigIntegerField()),
                ('website_link', models.TextField()),
                ('instagram_id', models.TextField()),
                ('telegram_id', models.TextField()),
                ('x_id', models.TextField()),
                ('card_number', models.PositiveBigIntegerField()),
                ('sheba_number', models.PositiveBigIntegerField()),
                ('address_portfolio', models.TextField()),
                ('image_portfolio', models.ImageField(upload_to='portfolio-picture')),
                ('CV_portfolio', models.FileField(upload_to='cv-portfolio')),
                ('location_link', models.TextField()),
                ('card_NO', models.IntegerField()),
                ('portfolio_views', models.IntegerField()),
            ],
        ),
    ]
