# Generated by Django 5.0.1 on 2024-02-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='mobile_portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='mobile_number_portfolio',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='CV_portfolio',
            field=models.FileField(null=True, upload_to='cv-portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='address_portfolio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='card_NO',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='card_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_portfolio',
            field=models.ImageField(null=True, upload_to='portfolio-picture'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='instagram_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='location_link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_views',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='sheba_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='telegram_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='website_link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='x_id',
            field=models.TextField(default=''),
        ),
    ]
