# Generated by Django 5.0.1 on 2024-02-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_portfolio_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='instagram_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='telegram_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='website_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='x_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
