# Generated by Django 5.0.1 on 2024-02-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_portfolio_instagram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='CV_portfolio',
            field=models.FileField(blank=True, null=True, upload_to='cv-portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='address_portfolio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='card_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_portfolio',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio-picture'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='instagram_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='location_link',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='mobile_number_portfolio',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='sheba_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='website_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='x_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
