# Generated by Django 5.0.1 on 2024-02-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
