# Generated by Django 5.0.1 on 2024-02-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_customeradddress_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.portfolio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
