# Generated by Django 5.0.3 on 2024-03-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_order_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='facebook_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ita_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='linkedIn_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='mastecard_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='payPal_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='roobika',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='snapchat_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='visaCard_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='whatsApp_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='youtube_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
