# Generated by Django 5.0.3 on 2024-03-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_created_at_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='card_NO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
