# Generated by Django 5.0.3 on 2024-03-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_portfolio_card_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
